module fr {
module corba {
module idl {
module Code {

	exception IdAlreadyUsed {};
	exception NameAlreadyUsed {};
	exception UnknownID {};
	exception WrongPassword {};
	
	struct Avatar {
		long id;
		string pseudo;
		string code_acces;
		string taille;
		string humeur;
		string sexe;
		long id_piece;
		boolean est_admin;
		boolean est_connecte;
	};
	
	typedef sequence<Avatar> Avatars;
	
	struct Post {
		long id;
		string contenu;
		string date_heure;
		long id_avatar;
	};
	
	struct Piece {
		long id;
		long posX;
		long posY;
		string nom;
		long id_nord;
		long id_sud;
		long id_est;
		long id_ouest;
		Avatars avatars;
	};
	
	interface User{
		void receiveChatMessage(in string nick, in string text);
		void receiveKicked();
		
		void receivePiece(in Piece Piece);
		void receiveMoved(in string nick, in short x, in short y);
	};
	
	interface Admin : User{
		void receiveExistingAvatars(in Object list);
		void receiveIsKicked(in boolean kicked);
		void receivePieceContent(in Piece Piece);
		void receiveConnectedUsers(in Object list);
	};
	interface Server
	{
		string subscribe(in string nick, in string password, in User c) raises (NameAlreadyUsed, WrongPassword);
		void unsubscribe(in string myId) raises (UnknownID);
		void comment(in string myId, in string text) raises (UnknownID);
		string addUser(in string nick, in string taille, in string humeur) raises (NameAlreadyUsed);
		boolean isAdmin(in string nick, in string password);
		Avatars requestExistingAvatars();		
		void requestKick(in string nick) raises(UnknownID);
		Avatar getAvatar(in string nick);
		
		void requestMove(in short x, in short y);
		void changePiece(in string myId);		
		Piece requestPieceContent(in long idPiece);
	};

};
};
};
};
