
package ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MyServiceService", targetNamespace = "http://server.ws/", wsdlLocation = "http://localhost:8080/ws/MyService?wsdl")
public class MyServiceService
    extends Service
{

    private final static URL MYSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException MYSERVICESERVICE_EXCEPTION;
    private final static QName MYSERVICESERVICE_QNAME = new QName("http://server.ws/", "MyServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/MyService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYSERVICESERVICE_WSDL_LOCATION = url;
        MYSERVICESERVICE_EXCEPTION = e;
    }

    public MyServiceService() {
        super(__getWsdlLocation(), MYSERVICESERVICE_QNAME);
    }

    public MyServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYSERVICESERVICE_QNAME, features);
    }

    public MyServiceService(URL wsdlLocation) {
        super(wsdlLocation, MYSERVICESERVICE_QNAME);
    }

    public MyServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYSERVICESERVICE_QNAME, features);
    }

    public MyServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MyService
     */
    @WebEndpoint(name = "MyServicePort")
    public MyService getMyServicePort() {
        return super.getPort(new QName("http://server.ws/", "MyServicePort"), MyService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyService
     */
    @WebEndpoint(name = "MyServicePort")
    public MyService getMyServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.ws/", "MyServicePort"), MyService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYSERVICESERVICE_EXCEPTION!= null) {
            throw MYSERVICESERVICE_EXCEPTION;
        }
        return MYSERVICESERVICE_WSDL_LOCATION;
    }

}
