
package ws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyService", targetNamespace = "http://server.ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<ws.client.Post>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMessages", targetNamespace = "http://server.ws/", className = "ws.client.GetMessages")
    @ResponseWrapper(localName = "getMessagesResponse", targetNamespace = "http://server.ws/", className = "ws.client.GetMessagesResponse")
    @Action(input = "http://server.ws/MyService/getMessagesRequest", output = "http://server.ws/MyService/getMessagesResponse")
    public List<Post> getMessages(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTemperature", targetNamespace = "http://server.ws/", className = "ws.client.GetTemperature")
    @ResponseWrapper(localName = "getTemperatureResponse", targetNamespace = "http://server.ws/", className = "ws.client.GetTemperatureResponse")
    @Action(input = "http://server.ws/MyService/getTemperatureRequest", output = "http://server.ws/MyService/getTemperatureResponse")
    public int getTemperature(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
